export const FETCH_MANUFACTURE_REQUEST = "FETCH_MANUFACTURE_REQUEST"
export const FETCH_MANUFACTURE_SUCCESS = "FETCH_MANUFACTURE_SUCCESS"
export const FETCH_MANUFACTURE_ERROR = "FETCH_MANUFACTURE_ERROR"

export const MANUFACTURE_GET_LIST = "MANUFACTURE_GET_LIST"
export const MANUFACTURE_CREATE_NEW = "MANUFACTURE_CREATE_NEW"
export const MANUFACTURE_DELETE_BY_ID = "MANUFACTURE_DELETE_BY_ID"
export const MANUFACTURE_GET_SINGLE = "MANUFACTURE_GET_SINGLE"
export const MANUFACTURE_EDIT_BY_ID = "MANUFACTURE_EDIT_BY_ID"