// export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST"
// export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"
// export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR"

// export const PRODUCT_LOAD_START = "PRODUCT_LOAD_START"
// export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS"
// export const PRODUCT_LOAD_ERROR = "PRODUCT_LOAD_ERROR"

// export const PRODUCT_CREATE = "PRODUCT_CREATE"

export const PRODUCT_GET_LIST = "PRODUCT_GET_LIST"
export const PRODUCT_CREATE_NEW = "PRODUCT_CREATE_NEW"
export const PRODUCT_CREATE_NEW_FAIL = "PRODUCT_CREATE_NEW_FAIL"
export const PRODUCT_DELETE_BY_ID = "PRODUCT_DELETE_BY_ID"
export const PRODUCT_GET_SINGLE = "PRODUCT_GET_SINGLE"
export const PRODUCT_EDIT_BY_ID = "PRODUCT_EDIT_BY_ID"
export const PRODUCT_GET_STATUS = "PRODUCT_GET_STATUS"
export const PRODUCT_GET_BY_CATEGORY = "PRODUCT_GET_BY_CATEGORY"