// export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
// export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
// export const FETCH_USER_ERROR = "FETCH_USER_ERROR"

// export const USER_LOAD_START = "USER_LOAD_START"
// export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
// export const USER_LOAD_ERROR = "USER_LOAD_ERROR"

// export const USER_CREATE = "USER_CREATE"

export const USER_GET_LIST = "USER_GET_LIST"
export const USER_CREATE_NEW = "USER_CREATE_NEW"
export const USER_CREATE_NEW_FAIL = "USER_CREATE_NEW_FAIL"
export const USER_DELETE_BY_ID = "USER_DELETE_BY_ID"
export const USER_GET_SINGLE = "USER_GET_SINGLE"
export const USER_EDIT_BY_ID = "USER_EDIT_BY_ID"
export const USER_GET_STATUS = "USER_GET_STATUS"
export const USER_SAVE_CART = "USER_SAVE_CART"